# your master list of topics
# 20 universal categories
topics = [
    "Religion & Belief",
    "Computing, AI & Data",
    "Hardware & Devices",
    "Security & Cryptography",
    "Engineering (Electrical, Mechanical & Systems)",
    "Physical Sciences (Physics, Chemistry & Materials)",
    "Mathematics & Foundations",
    "Life Sciences & Biotechnology",
    "Medicine & Public Health",
    "Space & Astronomy",
    "Earth, Environment & Climate",
    "Economics, Finance & Markets",
    "Business, Work & Personal Finance",
    "Politics, Law & Public Policy",
    "International Relations & Geopolitics",
    "Social & Behavioral Sciences",
    "Transportation & Mobility",
    "Sports",
    "Arts, Media & Entertainment",
    "Culture, Lifestyle & Travel",
]

# News (20NG) -> category
news_map = {
    "alt.atheism": "Religion & Belief",
    "comp.graphics": "Computing, AI & Data",
    "comp.os.ms-windows.misc": "Computing, AI & Data",
    "comp.sys.ibm.pc.hardware": "Hardware & Devices",
    "comp.sys.mac.hardware": "Hardware & Devices",
    "comp.windows.x": "Computing, AI & Data",
    "misc.forsale": "Business, Work & Personal Finance",
    "rec.autos": "Transportation & Mobility",
    "rec.motorcycles": "Transportation & Mobility",
    "rec.sport.baseball": "Sports",
    "rec.sport.hockey": "Sports",
    "sci.crypt": "Security & Cryptography",
    "sci.electronics": "Engineering (Electrical, Mechanical & Systems)",
    "sci.med": "Medicine & Public Health",
    "sci.space": "Space & Astronomy",
    "soc.religion.christian": "Religion & Belief",
    "talk.politics.guns": "Politics, Law & Public Policy",
    "talk.politics.mideast": "International Relations & Geopolitics",
    "talk.politics.misc": "Politics, Law & Public Policy",
    "talk.religion.misc": "Religion & Belief",
}

# Academic (arXiv-style) -> category
academic_map = {
    "acc-phys": "Physical Sciences (Physics, Chemistry & Materials)",
    "adap-org": "Mathematics & Foundations",
    "alg-geom": "Mathematics & Foundations",
    "ao-sci": "Earth, Environment & Climate",
    "astro-ph": "Space & Astronomy",
    "atom-ph": "Physical Sciences (Physics, Chemistry & Materials)",
    "bayes-an": "Mathematics & Foundations",
    "chao-dyn": "Mathematics & Foundations",
    "chem-ph": "Physical Sciences (Physics, Chemistry & Materials)",
    "cmp-lg": "Computing, AI & Data",
    "comp-gas": "Mathematics & Foundations",
    "cond-mat": "Physical Sciences (Physics, Chemistry & Materials)",
    "cs": "Computing, AI & Data",
    "dg-ga": "Mathematics & Foundations",
    "econ": "Economics, Finance & Markets",
    "eess": "Engineering (Electrical, Mechanical & Systems)",
    "funct-an": "Mathematics & Foundations",
    "gr-qc": "Space & Astronomy",
    "hep-ex": "Physical Sciences (Physics, Chemistry & Materials)",
    "hep-lat": "Physical Sciences (Physics, Chemistry & Materials)",
    "hep-ph": "Physical Sciences (Physics, Chemistry & Materials)",
    "hep-th": "Physical Sciences (Physics, Chemistry & Materials)",
    "math": "Mathematics & Foundations",
    "math-ph": "Mathematics & Foundations",
    "mtrl-th": "Physical Sciences (Physics, Chemistry & Materials)",
    "nlin": "Mathematics & Foundations",
    "nucl-ex": "Physical Sciences (Physics, Chemistry & Materials)",
    "nucl-th": "Physical Sciences (Physics, Chemistry & Materials)",
    "patt-sol": "Mathematics & Foundations",
    "physics": "Physical Sciences (Physics, Chemistry & Materials)",
    "plasm-ph": "Physical Sciences (Physics, Chemistry & Materials)",
    "q-alg": "Mathematics & Foundations",
    "q-bio": "Life Sciences & Biotechnology",
    "q-fin": "Economics, Finance & Markets",
    "quant-ph": "Physical Sciences (Physics, Chemistry & Materials)",
    "solv-int": "Mathematics & Foundations",
    "stat": "Mathematics & Foundations",
    "supr-con": "Physical Sciences (Physics, Chemistry & Materials)",
}

# Social flairs/tags -> category
social_map = {
    "ADOPTION": "Culture, Lifestyle & Travel",
    "ADVICE": "Culture, Lifestyle & Travel",
    "AI": "Computing, AI & Data",
    "AMA": "Culture, Lifestyle & Travel",
    "ANALYSIS": "Culture, Lifestyle & Travel",
    "ANECDOTAL": "Culture, Lifestyle & Travel",
    "Academic": "Social & Behavioral Sciences",
    "Analysis": "Culture, Lifestyle & Travel",
    "Animal Science": "Life Sciences & Biotechnology",
    "Anthropology": "Social & Behavioral Sciences",
    "Archaeology": "Social & Behavioral Sciences",
    "Article": "Arts, Media & Entertainment",
    "Astronomy": "Space & Astronomy",
    "Auto": "Transportation & Mobility",
    "Biology": "Life Sciences & Biotechnology",
    "Budgeting": "Business, Work & Personal Finance",
    "COMEDY": "Arts, Media & Entertainment",
    "COVID-19": "Medicine & Public Health",
    "Cancer": "Medicine & Public Health",
    "Career Discussion": "Business, Work & Personal Finance",
    "Career | Europe": "Business, Work & Personal Finance",
    "Career | US": "Business, Work & Personal Finance",
    "Challenges": "Culture, Lifestyle & Travel",
    "Chemistry": "Physical Sciences (Physics, Chemistry & Materials)",
    "Coding": "Computing, AI & Data",
    "Computer Science": "Computing, AI & Data",
    "Computing": "Computing, AI & Data",
    "Credit": "Business, Work & Personal Finance",
    "DE": "Culture, Lifestyle & Travel",
    "DEBATE": "Politics, Law & Public Policy",
    "DISCUSSION": "Culture, Lifestyle & Travel",
    "Debt": "Business, Work & Personal Finance",
    "Discussion": "Culture, Lifestyle & Travel",
    "Discusssion": "Culture, Lifestyle & Travel",
    "EXCHANGES": "Economics, Finance & Markets",
    "Earth Sciences": "Earth, Environment & Climate",
    "Economics": "Economics, Finance & Markets",
    "Education": "Social & Behavioral Sciences",
    "Employment": "Business, Work & Personal Finance",
    "Engineering": "Engineering (Electrical, Mechanical & Systems)",
    "Environment": "Earth, Environment & Climate",
    "Epidemiology": "Medicine & Public Health",
    "Ethics/Privacy": "Security & Cryptography",
    "Finance": "Economics, Finance & Markets",
    "GENERAL-NEWS": "Politics, Law & Public Policy",
    "Gaming": "Arts, Media & Entertainment",
    "Genetics": "Life Sciences & Biotechnology",
    "Geology": "Earth, Environment & Climate",
    "Gym Story Saturday": "Culture, Lifestyle & Travel",
    "Health": "Medicine & Public Health",
    "Housing": "Business, Work & Personal Finance",
    "Human Body": "Life Sciences & Biotechnology",
    "Image": "Arts, Media & Entertainment",
    "Images": "Arts, Media & Entertainment",
    "Insurance": "Business, Work & Personal Finance",
    "Investing": "Economics, Finance & Markets",
    "Itinerary": "Culture, Lifestyle & Travel",
    "LEGACY": "Culture, Lifestyle & Travel",
    "Linguistics": "Social & Behavioral Sciences",
    "MARKETS": "Economics, Finance & Markets",
    "MEME": "Arts, Media & Entertainment",
    "METRICS": "Economics, Finance & Markets",
    "MISLEADING": "Arts, Media & Entertainment",
    "ML": "Computing, AI & Data",
    "Materials Science": "Physical Sciences (Physics, Chemistry & Materials)",
    "Mathematics": "Mathematics & Foundations",
    "Media": "Arts, Media & Entertainment",
    "Medicine": "Medicine & Public Health",
    "Megathread": "Culture, Lifestyle & Travel",
    "Meta": "Culture, Lifestyle & Travel",
    "Mod Post": "Culture, Lifestyle & Travel",
    "Monday Meme": "Arts, Media & Entertainment",
    "Moronic Monday": "Arts, Media & Entertainment",
    "MoviesTV": "Arts, Media & Entertainment",
    "My Advice": "Culture, Lifestyle & Travel",
    "NEW UPDATE - See Pinned Comment.": "Culture, Lifestyle & Travel",
    "NFTs": "Economics, Finance & Markets",
    "Nanoscience": "Physical Sciences (Physics, Chemistry & Materials)",
    "Neuroscience": "Life Sciences & Biotechnology",
    "News": "Politics, Law & Public Policy",
    "Official Discussion": "Politics, Law & Public Policy",
    "Other": "Culture, Lifestyle & Travel",
    "PERSPECTIVE": "Politics, Law & Public Policy",
    "POLITICS": "Politics, Law & Public Policy",
    "PRIVACY": "Security & Cryptography",
    "PROJECT-UPDATE": "Engineering (Electrical, Mechanical & Systems)",
    "Paleontology": "Earth, Environment & Climate",
    "Physics": "Physical Sciences (Physics, Chemistry & Materials)",
    "Physique Phriday": "Culture, Lifestyle & Travel",
    "Planetary Sci.": "Space & Astronomy",
    "Planning": "Culture, Lifestyle & Travel",
    "Poster": "Arts, Media & Entertainment",
    "Project": "Engineering (Electrical, Mechanical & Systems)",
    "Projects": "Engineering (Electrical, Mechanical & Systems)",
    "Psychology": "Social & Behavioral Sciences",
    "Question": "Culture, Lifestyle & Travel",
    "REGULATIONS": "Politics, Law & Public Policy",
    "REMINDER": "Culture, Lifestyle & Travel",
    "Recommendation": "Culture, Lifestyle & Travel",
    "Research": "Physical Sciences (Physics, Chemistry & Materials)",
    "Retirement": "Business, Work & Personal Finance",
    "Review": "Arts, Media & Entertainment",
    "SCALABILITY": "Engineering (Electrical, Mechanical & Systems)",
    "SPECULATION": "Economics, Finance & Markets",
    "STRATEGY": "Economics, Finance & Markets",
    "Saving": "Business, Work & Personal Finance",
    "Science": "Physical Sciences (Physics, Chemistry & Materials)",
    "Simple Questions": "Culture, Lifestyle & Travel",
    "Social Science": "Social & Behavioral Sciences",
    "Spoilers": "Arts, Media & Entertainment",
    "Statistics": "Mathematics & Foundations",
    "TECHNOLOGY": "Computing, AI & Data",
    "Taxes": "Economics, Finance & Markets",
    "Tech": "Computing, AI & Data",
    "Third Party Horror Story": "Culture, Lifestyle & Travel",
    "Tools": "Computing, AI & Data",
    "Trailer": "Arts, Media & Entertainment",
    "Travel": "Culture, Lifestyle & Travel",
    "VIDEOS": "Arts, Media & Entertainment",
    "Victory Sunday": "Sports",
    "Video": "Arts, Media & Entertainment",
    "WARNING": "Arts, Media & Entertainment",
    "[Locked]": "Culture, Lifestyle & Travel",
    "[Misleading - Only some backers]": "Arts, Media & Entertainment",
    "eXch Competition - 0.5 BTC Prize!": "Economics, Finance & Markets",
    "⛏️ MINING": "Economics, Finance & Markets",
    "⛏️ See Top Comment.": "Economics, Finance & Markets",
    "🔴 UNRELIABLE SOURCE": "Arts, Media & Entertainment",
    "🟢 ANALYSIS": "Culture, Lifestyle & Travel",
    "🟢 DISCUSSION": "Culture, Lifestyle & Travel",
    "🟢 GENERAL-NEWS": "Politics, Law & Public Policy",
    "🟢 MARKETS": "Economics, Finance & Markets",
    "🟢 METRICS": "Economics, Finance & Markets",
    "🟢 POLITICS": "Politics, Law & Public Policy",
    "🟢 SPECULATION": "Economics, Finance & Markets",
    "🟢 ⛏️ MINING": "Economics, Finance & Markets",
}


import os
import pandas as pd

# Assert all mapping values are in the master topic list
for _map, _name in zip([news_map, academic_map, social_map], ["news_map", "academic_map", "social_map"]):
    invalid = [v for v in _map.values() if v not in topics]
    assert not invalid, f"{_name} contains invalid topics: {invalid}"

if __name__ == "__main__":
    # Load combined.csv
    raw_dir = os.path.join( 'data', 'raw')
    combined_path = os.path.join(raw_dir, 'combined.csv')
    df = pd.read_csv(combined_path)

    # Apply mapping based on domain
    def map_target(row):
        if row['domain'] == 'news':
            return news_map.get(row['target'], None)
        elif row['domain'] == 'academic':
            return academic_map.get(row['target'], None)
        elif row['domain'] == 'social':
            return social_map.get(row['target'], None)
        else:
            return None

    df['target'] = df.apply(map_target, axis=1)

    # Save to combined_mapped.csv
    mapped_path = os.path.join(raw_dir, 'combined_mapped.csv')
    df.to_csv(mapped_path, index=False)
    print(f"Mapped combined dataset saved to {mapped_path}")